name: 检查链接

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 这个设置为每天午夜UTC运行

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: 运行链接检查脚本
      run: |
        python check_links.py

    - name: 上传无法访问的链接
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: inaccessible-links
        path: inaccessible_links.txt
